### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AGSPhoenix** [shiimizu/thumb-gen#6]
This image causes the latest static build to segfault, regardless of OP/reply and SFW/NSFW:

http://s2.desu-usergeneratedcontent.xyz/mlp/image/1420/84/1420846635059.png

The image is 8-bit grayscale with alpha, a very uncommon format. I don't know for sure that that's relevant, but it seems like quite a coincidence if not.

**Comment by shiimizu** [comment]
Fixed in b122b7f
